### ISSUE TITLE
Use this with Handlebars?

### ISSUE THREAD

**Issue by andeersg** [expressjs/express-messages#13]
Is it possible to use this module with handlebars as a view engine?

I'm not sure how to implement it.

**Comment by ERPedersen** [comment]
bump

**Comment by di-ego02** [comment]
when you utilize this code`app.use(require('connect-flash')());
app.use(function (req, res, next) {
  res.locals.messages = require('express-messages')(req, res);
  next();
});` taken from the documentation here it specifies that you need to invoke res.local.messages in your template, i e <%-messages()%> but in handlebars you can't write js in the curly braces. So we must call res.local.messages before hand, i e ` res.locals.messages = require('express-messages')(req, res)();` which will return the flash message object! in your handlebar template you access the key 'messages' like this `{{{messages}}}`

**Comment by artcommacode** [comment]
Thanks @di-ego02, can you confirm this work for you @andeersg, @ERPedersen?

**Comment by andeersg** [comment]
Yes, I have done something similar (or exactly the same I see):

``` JS
app.use(flash());
app.use(function (req, res, next) {
  res.locals.messages = require('express-messages')(req, res);
  next();
});
```

So I guess we can close this :)

**Comment by artcommacode** [comment]
Thanks for the confirmation.

**Comment by ERPedersen** [comment]
Works for me too :) I did somewhat the same :+1:

**Comment by artcommacode** [comment]
Good to hear, I'll try and add it to the docs once I get the chance.

**Comment by Gauravkandpal001** [comment]
Thanks de-ego02  you solved my issue of using handlebars with express.

**Comment by dalalRohit** [comment]
@Gauravkandpal001  Can you show me how did you write the handlebars template code for this? I'm stuck on that only.

**Comment by Gauravkandpal001** [comment]
@dalalRohit My error was I forgot to add **( )** at the end of below line of code. :
res.locals.messages = require('express-messages')(req, res)();   
in handlebars use :      {{{message}}}       
to display your message


<div class="col_12">
<div class="col_9">
{{{messages}}}
{{#if errors}}
{{#each errors}}
<div class="notice error"><i class="icon-remove-sign icon-large"></i>
{{msg}}
<a href="#close" class="icon-remove"></a>
</div>
{{/each}}
{{/if}}
{{{body}}}
</div>
<div class="col_3">
{{>login}}
</div>
