### ISSUE TITLE
custom template with EJS

### ISSUE THREAD

**Issue by jaouadballat** [expressjs/express-messages#18]
When i'm adding a custom template with EJS it doesn't show anything and i found that's Express 4 doesn't support express-messages is that true?
`<div id="messages">
<% Object.keys(messages).forEach(function (type) { %>
  <ul class="<%= type %>">
  <% messages[type].forEach(function (message) { %>
    <li><%= message %></li>
  <% }) %>
  </ul>
<% }) %>
</div>`

**Comment by qtech** [comment]
It is still supported. I developed an app using express@4.16.3
Please provide test case to check what is wrong. Good luck though.
