### ISSUE TITLE
Is this repo still under maintainance ?

### ISSUE THREAD

**Issue by medmin** [expressjs/express-messages#19]
The latest commit was in 2016.
So....

**Comment by dougwilson** [comment]
I'm not familiar with this repo. Let's give more than 2 hours for someone to respond :)

**Comment by artcommacode** [comment]
It's currently 22:00 on a Bank Holiday here, I'll respond to ya'll in the morning. Thanks doug.

**Comment by artcommacode** [comment]
Hi @medmin, is there anything in particular you think should be done with `express-messages`? At it's heart it's just a dozen lines of code that builds some html, there's not a lot to it. The heavy work is done by https://github.com/jaredhanson/connect-flash which itself hasn't been updated in 5 years!

@mlosh I see you have a pull request open to change `Jade` to `Pug` in the docs, which is fair enough, I can look at that for you.

**Comment by dougwilson** [comment]
I have been generous with the time and there has been no response. I'm moving this repo to the archive.
